In [ ]:
import torch

a = torch.tensor([1.0, 2, 3, 4])

In [ ]:
b = torch.tensor([1.0, 2, 3, 4])
b.requires_grad = True

In [ ]:
c = a*b
c

tensor([ 1.,  4.,  9., 16.], grad_fn=<MulBackward0>)

In [ ]:
c = a + b
c

tensor([2, 4, 6, 8])

In [ ]:
a = torch.tensor([[1, 2],
                  [3, 4]])
b = torch.tensor([[1, 2],
                  [3, 4]])

c = torch.matmul(a, b)
c

tensor([[ 7, 10],
        [15, 22]])

In [ ]:
a @ b

tensor([[ 7, 10],
        [15, 22]])

In [ ]:
c.max(dim=1)

torch.return_types.max(
values=tensor([10, 22]),
indices=tensor([1, 1]))

In [ ]:
c.argmax(dim=1)

tensor([1, 1])

In [ ]:
torch.exp(c)

tensor([[1.0966e+03, 2.2026e+04],
        [3.2690e+06, 3.5849e+09]])

In [ ]:
a.matmul(b)

tensor([[ 7, 10],
        [15, 22]])

In [ ]:
c.sum(dim=1)

tensor([17, 37])