In [ ]:
import torch

In [ ]:
x = torch.tensor([1, 2, 3, 4]).view(1, 4)
w = torch.tensor([1, 2, 3, 4]).view(4, 1)
print(x)
print(w)

tensor([[1, 2, 3, 4]])
tensor([[1],
        [2],
        [3],
        [4]])


In [ ]:
y = x @ w
y

tensor([[30]])